### PR TITLE
Correct spec to allow source parameter

### PR DESCRIPTION
**Pull request by ab77**
Change-type: patch

### CODE REVIEW

**Comment by ab77** [comment]
@balena-ci I self-certify!

**Comment by 20k-ultra** [comment]
I believe this change broke the action. I just ran the action and found this. Note `--source /github/workspace/false`

```
 /usr/bin/balena push balena_os/armv7hf-supervisor --source /github/workspace/false --release-tag balena-ci-commit-sha 526787c3711a3ab3d0c8e31c6ba61a6894e074b8 balena-ci-id 778848383 --draft
Could not access source folder: "/github/workspace/false"

Error: The process '/usr/bin/balena' failed with exit code 1
```

**Comment by Bucknalla** [comment]
@20k-ultra I believe this is where the error is coming from ->  [default: false](https://github.com/balena-io/balena-ci/blob/f7f77ad70b5b1943ad19e0aa3619af0099dd9f9b/action.yml#L38) in the action.yml

**Comment by Bucknalla** [comment]
The default value should be an empty string as we want the root directory

**Pull request merged**
